run:
  concurrency: 6
  timeout: 1m
  tests: false
  skip-dirs-use-default: true
  linters:
  disable-all: true
  enable:
    - govet 
    - goconst 
    - funlen 
    - bodyclose 
    - errcheck 
    - deadcode 
    - exportloopref
    - gocyclo
    - goreporter 
  linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 50
